### ISSUE TITLE
slashpreserver capturing all slashes

### ISSUE THREAD

**Issue by deprekate** [perkint/slashpreserver#1]
While typing an email in GMail, I needed to give someone a path to a file.  I went to type "/home/..." but SP constantly catches the slash button press and redirects to the Firefox find function.  I had to open a terminal, type a slash, then copy-paste it into my email.

**Comment by perkint** [comment]
Thanks for the report.

I believe this problem is real but I do not have a gmail account (and am not willing to get one), so I'm not able to troubleshoot this myself.

If you look at the source code in main.js, you'll see that it tries to avoid this problem by testing for input from HTMLTextAreaElement, etc..

I'm not too interested in a patch that is gmail specific, but if you can identify a similarly generic test for the event.originalTarget gmail is using, perhaps by inspecting it with firebug, I would welcome a patch.

**Comment by deprekate** [comment]
Yup, I do see the target check in main.js.   It looks like GMail uses an editable div as its area for typing an email.

`<div tabindex="1" style="direction: ltr; min-height: 85px;" role="textbox" g_editable="true" id=":21d" class="Am Al editable LW-avf" hidefocus="true" aria-label="Message Body" contenteditable="true">This is what I just typed into the GMail compose window.<br></div>`

Perhaps, also checking for "contenteditable=true" or "role=textbox"? This might also make SP more future proof as other websites move into HTML5?

**Comment by deprekate** [comment]
I just realized I also cannot type a slash into Facebook post replies.

Facebook also uses the editable divs.
`<div id="js_21" title="Write a comment..." role="combobox" aria-autocomplete="list" aria-expanded="false" aria-owns="js_1w" aria-haspopup="false" class="_54-z" data-testid="ufi_comment_composer" spellcheck="true" data-reactid=".3g.1:5.0.$right.0.0.0.0.1.0.0.1.0" contenteditable="true"></div>`

So checking for "contenteditable=true" might be the best?

**Comment by perkint** [comment]
Thanks for your help.

I've updated the addon to check for contenteditable.

It works on this demo site for me:

  http://html5doctor.com/the-contenteditable-attribute/

Maybe it now also works on the sites you are interested in?

**Comment by deprekate** [comment]
Yup it works perfect.  Thanks so much, I have been looking for the last year on and off for a solution to the slash issue, and nothing else worked.
